name: dates_gen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2
  - torchvision
  - pytorch-cuda=12.1        # remove this line if no CUDA
  - numpy
  - matplotlib
  - tqdm
  - pip
  - pip:
    - scipy
